{% set name = "libtmux" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21955c5dce6332db41abad5e26ae8c4062ef2b9a89099bd57a36f52be1d5270f

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0
  run:
    - python >=3.8
    - tmux
    - __unix

test:
  imports:
    - libtmux
    - libtmux.session
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://libtmux.git-pull.com/
  doc_url: https://libtmux.git-pull.com/
  dev_url: https://github.com/tmux-python/libtmux
  summary: Python API / wrapper for tmux
  description: |
    libtmux is a typed Python library that provides a wrapper for interacting programmatically
    with tmux, a terminal multiplexer. You can use it to manage tmux servers, sessions, windows,
    and panes.
    Additionally, libtmux powers tmuxp, a tmux workspace manager.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoinePrv
    - tony
