{% set name = "libtmux" %}
{% set version = "0.42.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a13bc98d85fdb7105eea880d8f7017c8c4cca6563485972dd4550c57b66ee6f

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - tmux
    - __unix

test:
  imports:
    - libtmux
    - libtmux.session
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://libtmux.git-pull.com/
  doc_url: https://libtmux.git-pull.com/
  dev_url: https://github.com/tmux-python/libtmux
  summary: Python API / wrapper for tmux
  description: |
    libtmux is a typed Python library that provides a wrapper for interacting programmatically
    with tmux, a terminal multiplexer. You can use it to manage tmux servers, sessions, windows,
    and panes.
    Additionally, libtmux powers tmuxp, a tmux workspace manager.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoinePrv
    - tony
